extend type Mutation {
  """
  ✨ Insert a single `DeliveryJob` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  deliveryJob_insert(
    """
    Data object to insert into the table.
    """
    data: DeliveryJob_Data!
  ): DeliveryJob_KeyOutput! @fdc_generated(from: "DeliveryJob", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `LocationHistory` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  locationHistory_insert(
    """
    Data object to insert into the table.
    """
    data: LocationHistory_Data!
  ): LocationHistory_KeyOutput! @fdc_generated(from: "LocationHistory", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Package` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  package_insert(
    """
    Data object to insert into the table.
    """
    data: Package_Data!
  ): Package_KeyOutput! @fdc_generated(from: "Package", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Review` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  review_insert(
    """
    Data object to insert into the table.
    """
    data: Review_Data!
  ): Review_KeyOutput! @fdc_generated(from: "Review", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert `DeliveryJob` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  deliveryJob_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [DeliveryJob_Data!]!
  ): [DeliveryJob_KeyOutput!]! @fdc_generated(from: "DeliveryJob", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `LocationHistory` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  locationHistory_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [LocationHistory_Data!]!
  ): [LocationHistory_KeyOutput!]! @fdc_generated(from: "LocationHistory", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Package` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  package_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Package_Data!]!
  ): [Package_KeyOutput!]! @fdc_generated(from: "Package", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Review` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  review_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Review_Data!]!
  ): [Review_KeyOutput!]! @fdc_generated(from: "Review", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `DeliveryJob` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DeliveryJob`.
  """
  deliveryJob_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: DeliveryJob_Data!
  ): DeliveryJob_KeyOutput! @fdc_generated(from: "DeliveryJob", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `LocationHistory` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `LocationHistory`.
  """
  locationHistory_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: LocationHistory_Data!
  ): LocationHistory_KeyOutput! @fdc_generated(from: "LocationHistory", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Package` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Package`.
  """
  package_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Package_Data!
  ): Package_KeyOutput! @fdc_generated(from: "Package", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Review` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Review`.
  """
  review_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Review_Data!
  ): Review_KeyOutput! @fdc_generated(from: "Review", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `DeliveryJob` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DeliveryJob`.
  """
  deliveryJob_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [DeliveryJob_Data!]!
  ): [DeliveryJob_KeyOutput!]! @fdc_generated(from: "DeliveryJob", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `LocationHistory` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `LocationHistory`.
  """
  locationHistory_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [LocationHistory_Data!]!
  ): [LocationHistory_KeyOutput!]! @fdc_generated(from: "LocationHistory", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Package` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Package`.
  """
  package_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Package_Data!]!
  ): [Package_KeyOutput!]! @fdc_generated(from: "Package", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Review` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Review`.
  """
  review_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Review_Data!]!
  ): [Review_KeyOutput!]! @fdc_generated(from: "Review", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `DeliveryJob` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `DeliveryJob` or `null` if not found.
  """
  deliveryJob_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DeliveryJob_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DeliveryJob_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: DeliveryJob_Data!
  ): DeliveryJob_KeyOutput @fdc_generated(from: "DeliveryJob", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `LocationHistory` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `LocationHistory` or `null` if not found.
  """
  locationHistory_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: LocationHistory_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: LocationHistory_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: LocationHistory_Data!
  ): LocationHistory_KeyOutput @fdc_generated(from: "LocationHistory", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Package` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Package` or `null` if not found.
  """
  package_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Package_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Package_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Package_Data!
  ): Package_KeyOutput @fdc_generated(from: "Package", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Review` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Review` or `null` if not found.
  """
  review_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Review_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Review_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Review_Data!
  ): Review_KeyOutput @fdc_generated(from: "Review", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update `DeliveryJob` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  deliveryJob_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: DeliveryJob_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: DeliveryJob_Data!
  ): Int! @fdc_generated(from: "DeliveryJob", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `LocationHistory` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  locationHistory_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: LocationHistory_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: LocationHistory_Data!
  ): Int! @fdc_generated(from: "LocationHistory", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Package` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  package_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Package_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Package_Data!
  ): Int! @fdc_generated(from: "Package", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Review` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  review_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Review_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Review_Data!
  ): Int! @fdc_generated(from: "Review", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `DeliveryJob` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  deliveryJob_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DeliveryJob_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DeliveryJob_FirstRow
  ): DeliveryJob_KeyOutput @fdc_generated(from: "DeliveryJob", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `LocationHistory` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  locationHistory_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: LocationHistory_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: LocationHistory_FirstRow
  ): LocationHistory_KeyOutput @fdc_generated(from: "LocationHistory", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Package` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  package_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Package_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Package_FirstRow
  ): Package_KeyOutput @fdc_generated(from: "Package", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Review` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  review_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Review_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Review_FirstRow
  ): Review_KeyOutput @fdc_generated(from: "Review", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete `DeliveryJob` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  deliveryJob_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: DeliveryJob_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "DeliveryJob", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `LocationHistory` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  locationHistory_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: LocationHistory_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "LocationHistory", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Package` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  package_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Package_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Package", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Review` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  review_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Review_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Review", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
}
